[package]
name = "roblox/wise-3d"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
Replicator = "remnantsofsiren/replicator2@1.3.7"
Cardinal = "remnantsofsiren/cardinal@1.7.2"
Promise = "evaera/promise@4.0.0"
LemonSignal = "data-oriented-house/lemonsignal@1.10.0"
TableUtil = "sleitnick/table-util@1.2.1"

[server-dependencies]
DataKeep = "noahrepublic/datakeep@5.0.0"
